__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd.yml',
]

output_dir: /Users/robertkrutsch/Documents/Code/VD/rtdetr/RT-DETR/rtdetr_pytorch/output/rtdetr_r50vd_6x_coco/
